version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ../db_files:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: toor
       #MYSQL_DATABASE: testdb 
       #MYSQL_USER: docky
       #MYSQL_PASSWORD: docky
     ports:
      - 3306:3306

   p71:
     depends_on:
       - db
     image: php:7.1
     build:
      context: .
      dockerfile: Dockerfile71
     links:
      - db
     volumes:
      - ../:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./virtualhost-php71.conf:/etc/apache2/sites-available/001-virtualhost-php71.conf
      - ../logs/71_error_MIKI_task_redis.log:/var/www/71_error.log
      - ../logs/71_access_MIKI_task_redis.log:/var/www/71_access.log
     environment:
       DB_HOST: db:3306
       DB_PASSWORD: toor
     ports:
      - 89:80
     expose:
      - 9000

   redis:
      image: redis
      ports:
       - "6379:6379"

   pma:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "8080:80"
     volumes:
      - ../phpmyadmin/sessions:/sessions